filebeat.inputs:
  - type: filestream
    id: docker-containers
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*-json.log

    parsers:
      - ndjson:
          target: ""
          message_key: "log"

processors:
  - add_docker_metadata: ~

  # enlever le \n final de "message"
  - script:
      lang: javascript
      id: trim_message
      source: >
        function process(event) {
          var m = event.Get("message");
          if (m && typeof m === "string") {
            event.Put("message", m.replace(/\n$/, ""));
          }
        }

  # Décode JSON UNIQUEMENT pour certains containers
  # + UNIQUEMENT si message commence par "{"
  - decode_json_fields:
      when:
        and:
          - regexp:
              message: '^\s*\{'
          - or:
              - equals:
                  container.name: "auth-service"
              - equals:
                  container.name: "game-service"
              - equals:
                  container.name: "APIBC"
              - equals:
                  container.name: "APIBDD"
              # Optionnel : si tu veux aussi parser elastic/logstash/kibana en JSON (souvent inutile)
              # - equals: { container.name: "logstash" }
              # - equals: { container.name: "filebeat" }
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
