{
 "title": "General_metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (   rate(container_cpu_usage_seconds_total[1m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(   0.95,   sum by (le, job) (     rate(http_request_duration_seconds_bucket[1m])   ) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (   rate(http_requests_total[1m]) )",
     "legendFormat": "{{job}} - traffic (req/s)"
    }
   ]
  },
  {
   "title": "Service UP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}